version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    command: sleep infinity
    links:
      - database
      - rabbit
    volumes:
      - ..:/workspace:cached
  database:
    image: "postgres" # use latest official postgres version
    environment:
      - POSTGRES_PASSWORD=unicorn_user
      - POSTGRES_USER=magical_password
      - POSTGRES_DB=realworld
    restart: unless-stopped
    ports:
      - 5432:5432
  rabbit:
    image: "rabbitmq:3.8"
    ports:
      - 5672:5672
    restart: unless-stopped